// Runtime configuration.
//
// The SPA is account-agnostic: it does NOT bake AWS resource identifiers into
// the JS bundle at build time. Instead it fetches `/runtime-config.json` at
// startup. That file is generated by the FrontendStack at deploy time from the
// real CloudFormation outputs of the API and frontend stacks, so the same built
// bundle works in any account/region without a rebuild.

export interface RuntimeConfig {
  region: string;
  userPoolId: string;
  userPoolClientId: string;
  cognitoDomain: string;
  restApiUrl: string;
  wsApiUrl: string;
  cloudfrontUrl: string;
}

let cached: RuntimeConfig | null = null;

/**
 * Fetch and cache the runtime configuration. Must be awaited once during
 * application bootstrap before Amplify is configured or any API call is made.
 */
export async function loadRuntimeConfig(): Promise<RuntimeConfig> {
  if (cached) {
    return cached;
  }

  const res = await fetch('/runtime-config.json', { cache: 'no-store' });
  if (!res.ok) {
    throw new Error(`Failed to load runtime-config.json: ${res.status} ${res.statusText}`);
  }

  const raw = (await res.json()) as Record<string, string>;

  // Accept the VITE_-prefixed keys the deploy writes, mapping them to a clean shape.
  const config: RuntimeConfig = {
    region: raw.VITE_REGION,
    userPoolId: raw.VITE_USER_POOL_ID,
    userPoolClientId: raw.VITE_USER_POOL_CLIENT_ID,
    cognitoDomain: raw.VITE_COGNITO_DOMAIN,
    restApiUrl: raw.VITE_REST_API_URL,
    wsApiUrl: raw.VITE_WS_API_URL,
    cloudfrontUrl: raw.VITE_CLOUDFRONT_URL,
  };

  const missing = (Object.entries(config) as Array<[string, string]>)
    .filter(([, value]) => !value)
    .map(([key]) => key);
  if (missing.length > 0) {
    throw new Error(`runtime-config.json is missing required keys: ${missing.join(', ')}`);
  }

  cached = config;
  return config;
}

/**
 * Synchronous accessor for the already-loaded runtime configuration.
 * Throws if called before loadRuntimeConfig() has resolved.
 */
export function getConfig(): RuntimeConfig {
  if (!cached) {
    throw new Error('Runtime config accessed before loadRuntimeConfig() completed.');
  }
  return cached;
}
